#pragma once

#include "../AppMode.h"

namespace follow_v2 {

#define BU04_FOLLOW_V2_SCHEME_FIXED_1HZ 0
#define BU04_FOLLOW_V2_SCHEME_ROLLING_WINDOW 1

#if BU04_APP_MODE == BU04_APP_MODE_FOLLOW_V2_WINDOW
#define BU04_FOLLOW_V2_SCHEME BU04_FOLLOW_V2_SCHEME_ROLLING_WINDOW
#else
#define BU04_FOLLOW_V2_SCHEME BU04_FOLLOW_V2_SCHEME_FIXED_1HZ
#endif

#define BU04_FOLLOW_V2_ENABLE_FIXED_1HZ \
  (BU04_FOLLOW_V2_SCHEME == BU04_FOLLOW_V2_SCHEME_FIXED_1HZ)
#define BU04_FOLLOW_V2_ENABLE_ROLLING_WINDOW \
  (BU04_FOLLOW_V2_SCHEME == BU04_FOLLOW_V2_SCHEME_ROLLING_WINDOW)

}  // namespace follow_v2
